# Project: 实验4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 实验4.1.1.o 实验4.2.o 实验4.3.o 实验4.4.o 实验4.5.o 实验4.6.o 实验3.7.o 实验3.8.o
LINKOBJ  = 实验4.1.1.o 实验4.2.o 实验4.3.o 实验4.4.o 实验4.5.o 实验4.6.o 实验3.7.o 实验3.8.o
LIBS     = -L"D:/computerstudy/Dev C++/MinGW64/lib" -L"D:/computerstudy/Dev C++/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/computerstudy/Dev C++/MinGW64/include" -I"D:/computerstudy/Dev C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/computerstudy/Dev C++/MinGW64/lib/gcc/x86_64-w64-mingw32/7.1.0/include"
CXXINCS  = -I"D:/computerstudy/Dev C++/MinGW64/include" -I"D:/computerstudy/Dev C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/computerstudy/Dev C++/MinGW64/lib/gcc/x86_64-w64-mingw32/7.1.0/include" -I"D:/computerstudy/Dev C++/MinGW64/lib/gcc/x86_64-w64-mingw32/7.1.0/include/c++"
BIN      = 实验4.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

实验4.1.1.o: 实验4.1.1.c
	$(CC) -c 实验4.1.1.c -o 实验4.1.1.o $(CFLAGS)

实验4.2.o: 实验4.2.c
	$(CC) -c 实验4.2.c -o 实验4.2.o $(CFLAGS)

实验4.3.o: 实验4.3.c
	$(CC) -c 实验4.3.c -o 实验4.3.o $(CFLAGS)

实验4.4.o: 实验4.4.c
	$(CC) -c 实验4.4.c -o 实验4.4.o $(CFLAGS)

实验4.5.o: 实验4.5.c
	$(CC) -c 实验4.5.c -o 实验4.5.o $(CFLAGS)

实验4.6.o: 实验4.6.c
	$(CC) -c 实验4.6.c -o 实验4.6.o $(CFLAGS)

实验3.7.o: 实验3.7.c
	$(CC) -c 实验3.7.c -o 实验3.7.o $(CFLAGS)

实验3.8.o: 实验3.8.c
	$(CC) -c 实验3.8.c -o 实验3.8.o $(CFLAGS)
